var getRankings = new XMLHttpRequest();
getRankings.onload = function() {
  response = JSON.parse(getRankings.responseText);
  //pacific
  var pd1 = document.getElementById('pd1');
  pd1.textContent = response.conferences[1].divisions[1].teams[0].name;
  pd1.setAttribute("data-team", response.conferences[1].divisions[1].teams[0].id);
  var pd2 = document.getElementById('pd2');
  pd2.textContent = response.conferences[1].divisions[1].teams[1].name;
  pd2.setAttribute("data-team", response.conferences[1].divisions[1].teams[1].id);
  var pd3 = document.getElementById('pd3');
  pd3.textContent = response.conferences[1].divisions[1].teams[2].name;
  pd3.setAttribute("data-team", response.conferences[1].divisions[1].teams[2].id);
  var pd4 = document.getElementById('pd4');
  pd4.textContent = response.conferences[1].divisions[1].teams[3].name;
  pd4.setAttribute("data-team", response.conferences[1].divisions[1].teams[3].id);
  var pd5 = document.getElementById('pd5');
  pd5.textContent = response.conferences[1].divisions[1].teams[4].name;
  pd5.setAttribute("data-team", response.conferences[1].divisions[1].teams[4].id);
  var pd6 = document.getElementById('pd6');
  pd6.textContent = response.conferences[1].divisions[1].teams[5].name;
  pd6.setAttribute("data-team", response.conferences[1].divisions[1].teams[5].id);
  var pd7 = document.getElementById('pd7');
  pd7.textContent = response.conferences[1].divisions[1].teams[6].name;
  pd7.setAttribute("data-team", response.conferences[1].divisions[1].teams[6].id);
  //central
  var cd1 = document.getElementById('cd1');
  cd1.textContent = response.conferences[1].divisions[0].teams[0].name;
  cd1.setAttribute("data-team", response.conferences[1].divisions[0].teams[0].id);
  var cd2 = document.getElementById('cd2');
  cd2.textContent = response.conferences[1].divisions[0].teams[1].name;
  cd2.setAttribute("data-team", response.conferences[1].divisions[0].teams[1].id);
  var cd3 = document.getElementById('cd3');
  cd3.textContent = response.conferences[1].divisions[0].teams[2].name;
  cd3.setAttribute("data-team", response.conferences[1].divisions[0].teams[2].id);
  var cd4 = document.getElementById('cd4');
  cd4.textContent = response.conferences[1].divisions[0].teams[3].name;
  cd4.setAttribute("data-team", response.conferences[1].divisions[0].teams[3].id);
  var cd5 = document.getElementById('cd5');
  cd5.textContent = response.conferences[1].divisions[0].teams[4].name;
  cd5.setAttribute("data-team", response.conferences[1].divisions[0].teams[4].id);
  var cd6 = document.getElementById('cd6');
  cd6.textContent = response.conferences[1].divisions[0].teams[5].name;
  cd6.setAttribute("data-team", response.conferences[1].divisions[0].teams[5].id);
  var cd7 = document.getElementById('cd7');
  cd7.textContent = response.conferences[1].divisions[0].teams[6].name;
  cd7.setAttribute("data-team", response.conferences[1].divisions[0].teams[6].id);
  //atlantic
  var atld1 = document.getElementById('atld1');
  atld1.textContent = response.conferences[0].divisions[0].teams[0].name;
  atld1.setAttribute("data-team", response.conferences[0].divisions[0].teams[0].id);
  var atld2 = document.getElementById('atld2');
  atld2.textContent = response.conferences[0].divisions[0].teams[1].name;
  atld2.setAttribute("data-team", response.conferences[0].divisions[0].teams[1].id);
  var atld3 = document.getElementById('atld3');
  atld3.textContent = response.conferences[0].divisions[0].teams[2].name;
  atld3.setAttribute("data-team", response.conferences[0].divisions[0].teams[2].id);
  var atld4 = document.getElementById('atld4');
  atld4.textContent = response.conferences[0].divisions[0].teams[3].name;
  atld4.setAttribute("data-team", response.conferences[0].divisions[0].teams[3].id);
  var atld5 = document.getElementById('atld5');
  atld5.textContent = response.conferences[0].divisions[0].teams[4].name;
  atld5.setAttribute("data-team", response.conferences[0].divisions[0].teams[4].id);
  var atld6 = document.getElementById('atld6');
  atld6.textContent = response.conferences[0].divisions[0].teams[5].name;
  atld6.setAttribute("data-team", response.conferences[0].divisions[0].teams[5].id);
  var atld7 = document.getElementById('atld7');
  atld7.textContent = response.conferences[0].divisions[0].teams[6].name;
  atld7.setAttribute("data-team", response.conferences[0].divisions[0].teams[6].id);
  var atld8 = document.getElementById('atld8');
  atld8.textContent = response.conferences[0].divisions[0].teams[7].name;
  atld8.setAttribute("data-team", response.conferences[0].divisions[0].teams[7].id);
  //metropolitan
  var md1 = document.getElementById('md1');
  md1.textContent = response.conferences[0].divisions[1].teams[0].name;
  md1.setAttribute("data-team", response.conferences[0].divisions[1].teams[0].id);
  var md2 = document.getElementById('md2');
  md2.textContent = response.conferences[0].divisions[1].teams[1].name;
  md2.setAttribute("data-team", response.conferences[0].divisions[1].teams[1].id);
  var md3 = document.getElementById('md3');
  md3.textContent = response.conferences[0].divisions[1].teams[2].name;
  md3.setAttribute("data-team", response.conferences[0].divisions[1].teams[2].id);
  var md4 = document.getElementById('md4');
  md4.textContent = response.conferences[0].divisions[1].teams[3].name;
  md4.setAttribute("data-team", response.conferences[0].divisions[1].teams[3].id);
  var md5 = document.getElementById('md5');
  md5.textContent = response.conferences[0].divisions[1].teams[4].name;
  md5.setAttribute("data-team", response.conferences[0].divisions[1].teams[4].id);
  var md6 = document.getElementById('md6');
  md6.textContent = response.conferences[0].divisions[1].teams[5].name;
  md6.setAttribute("data-team", response.conferences[0].divisions[1].teams[5].id);
  var md7 = document.getElementById('md7');
  md7.textContent = response.conferences[0].divisions[1].teams[6].name;
  md7.setAttribute("data-team", response.conferences[0].divisions[1].teams[6].id);
  var md8 = document.getElementById('md8');
  md8.textContent = response.conferences[0].divisions[1].teams[7].name;
  md8.setAttribute("data-team", response.conferences[0].divisions[1].teams[7].id);
};
getRankings.open('GET', 'http://127.0.0.1:8080/rankings', true);
getRankings.send();

var getStandings = new XMLHttpRequest();
getStandings.onload = function() {
  response = JSON.parse(getStandings.responseText);
  console.log(response);
}
getStandings.open('GET', 'http://127.0.0.1:8080/standings', true);
getStandings.send();